INSERT INTO Atividade_Economica VALUES
(1, 'Extrativa mineral'),
(2, 'Minerais não-metálicos'),
(3, 'Indústria metalúrgica'),
(4, 'Indústria mecânica'),
(5, 'Indústria do material elétrico e de comunicações'),
(6, 'Indústria de material de transporte'),
(7, 'Indústria da madeira e do mobiliário'),
(8, 'Indústria do papel'),
(9, ' papelão'),
(10, ' editorial e gráfica'),
(11, 'Indústria da borracha'),
(12, ' fumo'),
(13, ' couros'),
(14, ' peles'),
(15, ' similares e diversas'),
(16, 'Indústria química de produtos farmacêuticos'),
(17, ' veterinários'),
(18, ' perfumaria...'),
(19, 'Indústria têxtil do vestuário e artefatos de tecidos'),
(20, 'Indústria de calçados'),
(21, 'Indústria de produtos alimentícios'),
(22, ' bebidas e álcool etílico'),
(23, 'Serviços industriais de utilidade pública '),
(24, 'Construção civil'),
(25, 'Comércio varejista'),
(26, 'Comércio atacadista'),
(27, 'Instituições de crédito'),
(28, ' seguros e capitalização'),
(29, 'Comércio e administração de imóveis'),
(30, ' valores mobiliários'),
(31, ' serviços técnicos'),
(32, 'Transportes e comunicações'),
(33, 'Serviços de alojamento'),
(34, ' alimentação'),
(35, ' reparação'),
(36, ' manutenção'),
(37, ' redação...'),
(38, 'Serviços médicos'),
(39, ' odontológicos e veterinários'),
(40, 'Ensino'),
(41, 'Administração pública direta e autárquica'),
(42, 'Agricultura'),
(43, ' silvicultura'),
(44, ' criação de animais'),
(45, ' extrativismo vegetal'),
(46, 'Outros/ignorado');