INSERT INTO Regiao_Administrativa VALUES 
(1, 'I Portuária'),
(2, 'II Centro'),
(3, 'III Rio Comprido'),
(4, 'VII São Cristóvão'),
(5, 'XXI Paquetá'),
(6, 'XXIII Santa Teresa'),
(7, 'IV Botafogo'),
(8, 'V Copacabana'),
(9, 'VI Lagoa'),
(10, 'XXVII Rocinha'),
(11, 'VIII Tijuca'),
(12, 'IX Vila Isabel'),
(13, 'X Ramos'),
(14, 'XXX Maré'),
(15, 'XIII Méier'),
(16, 'XXVIII Jacarezinho'),
(17, 'XIV Irajá'),
(18, 'XV Madureira'),
(19, 'XII Inhaúma'),
(20, 'XXIX Complexo do Alemão'),
(21, 'XI Penha'),
(22, 'XXXI Vigário Geral'),
(23, 'XXII Anchieta'),
(24, 'XXV Pavuna'),
(25, 'XX Ilha do Governador'),
(26, 'XVI Jacarepaguá'),
(27, 'XXXIV Cidade de Deus'),
(28, 'XXIV Barra da Tijuca'),
(29, 'XVII Bangu'),
(30, 'XXXIII Realengo'),
(31, 'XVIII Campo Grande'),
(32, 'XIX Santa Cruz'),
(33, 'XXVI Guaratiba');